var g_groundHight = 57;
var g_runnerStartX = 80;
var g_plateWidth = 50;
var g_plateHeight = 10;
var g_plateSpace = 30;
var g_marginSpace = 20;
var g_ballRadius = 5;
var g_ballLineWidth = 1;
var g_play_delay = 3000;
var g_game_ends = false;
var g_stairs = 0;
var g_left_color = cc.color(0, 0, 0, 255);			//黑色
var g_right_color = cc.color(255, 255, 255, 255); 	//白色
var g_plates = [];
var g_moving_interval = 300;						//方块匀速向下移动间隔
var g_moving_step = 2;								//方块匀速向下移动距离
var g_oriented_width = 105;
var g_oriented_height = 105;
var g_plate_oriented_width = 430;
var g_plate_oriented_height = 60;
var g_plate_bgs = {left : s_WhitePlate, right : s_BlackPlate};